//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AlliedRenewableEnergyLTD.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AlliedEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AlliedEntities object using the connection string found in the 'AlliedEntities' section of the application configuration file.
        /// </summary>
        public AlliedEntities() : base("name=AlliedEntities", "AlliedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AlliedEntities object.
        /// </summary>
        public AlliedEntities(string connectionString) : base(connectionString, "AlliedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AlliedEntities object.
        /// </summary>
        public AlliedEntities(EntityConnection connection) : base(connection, "AlliedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoginInfo> LoginInfos
        {
            get
            {
                if ((_LoginInfos == null))
                {
                    _LoginInfos = base.CreateObjectSet<LoginInfo>("LoginInfos");
                }
                return _LoginInfos;
            }
        }
        private ObjectSet<LoginInfo> _LoginInfos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoginInfos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoginInfos(LoginInfo loginInfo)
        {
            base.AddObject("LoginInfos", loginInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlliedModel", Name="LoginInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoginInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoginInfo object.
        /// </summary>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static LoginInfo CreateLoginInfo(global::System.String username, global::System.String password)
        {
            LoginInfo loginInfo = new LoginInfo();
            loginInfo.username = username;
            loginInfo.password = password;
            return loginInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                if (_username != value)
                {
                    OnusernameChanging(value);
                    ReportPropertyChanging("username");
                    _username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("username");
                    OnusernameChanged();
                }
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlliedModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="category">Initial value of the category property.</param>
        /// <param name="imagetype">Initial value of the imagetype property.</param>
        /// <param name="imagebytes">Initial value of the imagebytes property.</param>
        /// <param name="dateadded">Initial value of the dateadded property.</param>
        public static Product CreateProduct(global::System.Int32 id, global::System.String title, global::System.String category, global::System.String imagetype, global::System.Byte[] imagebytes, global::System.DateTime dateadded)
        {
            Product product = new Product();
            product.id = id;
            product.title = title;
            product.category = category;
            product.imagetype = imagetype;
            product.imagebytes = imagebytes;
            product.dateadded = dateadded;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.String _category;
        partial void OncategoryChanging(global::System.String value);
        partial void OncategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imagetype
        {
            get
            {
                return _imagetype;
            }
            set
            {
                OnimagetypeChanging(value);
                ReportPropertyChanging("imagetype");
                _imagetype = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imagetype");
                OnimagetypeChanged();
            }
        }
        private global::System.String _imagetype;
        partial void OnimagetypeChanging(global::System.String value);
        partial void OnimagetypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] imagebytes
        {
            get
            {
                return StructuralObject.GetValidValue(_imagebytes);
            }
            set
            {
                OnimagebytesChanging(value);
                ReportPropertyChanging("imagebytes");
                _imagebytes = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imagebytes");
                OnimagebytesChanged();
            }
        }
        private global::System.Byte[] _imagebytes;
        partial void OnimagebytesChanging(global::System.Byte[] value);
        partial void OnimagebytesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateadded
        {
            get
            {
                return _dateadded;
            }
            set
            {
                OndateaddedChanging(value);
                ReportPropertyChanging("dateadded");
                _dateadded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateadded");
                OndateaddedChanged();
            }
        }
        private global::System.DateTime _dateadded;
        partial void OndateaddedChanging(global::System.DateTime value);
        partial void OndateaddedChanged();

        #endregion

    
    }

    #endregion

    
}
